### ISSUE TITLE
[style] 프로필 이미지 제거

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#151]
## 📚  이슈

프로필 이미지 임시로 제거

## 📝  To-do

- [x] 정보 등록에 프로필 이미지 등록 버튼 숨기기
- [x] 마이페이지 프로필 이미지 숨기기
- [x] 채팅에서 프로필 이미지 숨기기
