### ISSUE TITLE
[feat] 최근 검색어 저장

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#193]
## 📚  이슈

최근 검색어 저장

## 📝  To-do

- [x] UserDefaults 이용해서 최근 검색어 저장하기
- [x] 저장된 검색어 클릭 시 검색 결과 표시하기
- [x] x 버튼을 눌러 검색 결과 삭제하기
