### ISSUE TITLE
[style] 목표 상세 오타 수정

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#196]
## 📚  이슈

목표 상세 오타 수정

## 📝  To-do

- [x] 완료한 목표에서 닉네임 뒤에 공백 제거하기
- [x] 진행 뒤에 공백 추가하기
- [x] 목표 상세에서 '오늘 기록은 이미 추가되었어요'로 수정하기
