### ISSUE TITLE
[refactor] 인증 로직 리팩토링

### ISSUE THREAD

**Issue by minnnidev** [BOOK-TALK/Readables-iOS#199]
## 📚  이슈

인증 로직 리팩토링

## 📝  To-do

- [ ] 토큰 갱신 로직 잘 되는지 테스트
- [x] 유저 정보 초기화 service 레이어에서
- [x] 카카오 유효성 검증 코드 추가
