### ISSUE TITLE
[feat] 책 상세 페이지 UI 구현

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#23]
## 📚  이슈

책 상세 페이지 UI 구현

## 📝  To-do

- [x] 테이블 뷰 생성
- [x] 내비게이션 바에 하트 버튼 생성
- [x] 0번째 섹션에는 책 이미지 및 정보 구현
- [x] 0번째 섹션에 하단에 '오픈톡 참여하기' 버튼 생성
- [x] 1번째 섹션에는 지도 및 거리 텍스트 구현
- [x] 우측 하단에 Floating Button 구현해보기 or 버튼 각각 테이블 뷰에 배치하기
- [x] accentGreen -> accentOrange로 변경하기
- [x] 검색 결과에서 셀 선택 시 책 상세 페이지로 이동하도록 연결하기
