### ISSUE TITLE
[feat] 프로젝트 초기 세팅 2

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#4]
## 📚  이슈

- 지원 기기, 앱 카테고리, 화면 방향, info.plist 수정
- ViewController, 메인 스토리보드 제거
- 폴더 구조 수정
- 불필요한 주석 제거 및 들여쓰기 추가

## 📝  To-do

- [x] 지원 기기 iPhone만 지원하도록 수정
- [x] 앱 카테고리 Books로 설정
- [x] 화면 방향 세로 모드만 지원하도록 수정
- [x] info.plist에서 Application Scene Main 제거
- [x] ViewController.swift, Main.storyboard 제거
- [x] 폴더 구조 변경
