### ISSUE TITLE
[feat] 검색 UI 수정 및 키워드 검색 구현

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#40]
## 📚  이슈

키워드로 검색하기 버튼 구현

## 📝  To-do

- [x] 스위치 버튼 추가하기
- [x] 키워드로 검색하기 구현하기
- [x] 대출 여부 데이터 연결하기
