### ISSUE TITLE
[feat] 책 상세 페이지 UI 수정

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#46]
## 📚  이슈

기존 지도와 실시간 위치 기능 구현은 취소되고 내가 설정한 도서관으로 표시되도록 수정

## 📝  To-do

- [x] 셀 이름 수정하기
- [x] 거리 데이터 제거하기
- [x] 설정한 도서관 없으면 보여줄 버튼 생성하기
- [x] 설정한 도서관 있으면 보여줄 도서관 대출 여부 텍스트 생성하기
