### ISSUE TITLE
[feat] 탭 바 구현

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#5]
## 📚  이슈

- UITabBarController로 탭 바 구현

## 📝  To-do

- [x] AppDelegate, SceneDelegate 파일 Application 폴더명으로 묶기
- [x] SceneDelegate 파일에 뷰 컨트롤러 연결하기
- [x] MainTabBarController 파일 생성 및 Presentation 폴더명으로 묶기
- [x] 라이트 모드만 지원하도록 info 수정하기
- [x] 홈, 카테고리, 오픈톡, 목표, 마이 뷰 컨트롤러 생성 및 탭 바 구현하기
- [x] 홈에 사용할 시스템 이미지: house, house.fill
- [x] 카테고리에 사용할 시스템 이미지: square.grid.2x2, square.grid.2x2.fill
- [x] 오픈톡에 사용할 시스템 이미지: message, message.fill
- [x] 목표에 사용할 시스템 이미지: chart.xyaxis.line
- [x] 마이에 사용할 시스템 이미지: person, person.fill
- [x] 틴트 컬러: 검정색
- [x] 배경: 하얀색
