### ISSUE TITLE
[feat] 로그인 UI 구현

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#55]
## 📚  이슈

로그인 UI 구현

## 📝  To-do

- [x] 온보딩 메시지 구현하기
- [x] 로티 애니메이션 추가하기
- [x] 애플, 카카오 로그인 추가하기
