### ISSUE TITLE
[feat] 카테고리 전체보기 필터에 따라 api 연결

### ISSUE THREAD

**Issue by minnnidev** [BOOK-TALK/Readables-iOS#69]
## 📝  To-do

- [ ] 랜덤순 api 연결
- [ ] 일주일 인기순 api 연결
- [ ] 한달 인기순 api 연결
- [ ] 신작 인기순 호출
- [ ] UI 반영
