### ISSUE TITLE
[feat] 내비게이션 바 UI 수정 및 버튼 구현

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#7]
## 📚  이슈

아래로 스크롤 시 내비게이션 바 감추고 위로 스크롤 시 다시 보이도록

## 📝  To-do

- [x] 내비게이션 바 검색 아이콘 버튼 구현하기
- [x] Hide and show navigation bar when scroll
- [x] 검색 아이콘 클릭 시 검색 화면으로 이동하기
