### ISSUE TITLE
[feat] 회원가입 UI 구현

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#94]
## 📚  이슈

회원가입 UI 구현

## 📝  To-do

- [x] 프로필 이미지 등록 버튼 구현하기
- [x] 닉네임 입력 필드 구현하기
- [x] 성별 버튼 구현하기
- [x] 데이트 피커 구현하기
