### ISSUE TITLE
[style] 책 상세페이지 UI 수정

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#97]
## 📚  이슈

책 상세페이지 UI 수정

## 📝  To-do

- [x] 텍스트 길이 길어졌을 때 레이아웃 깨짐 현상 해결하기
- [x] 도서관 등록하기 버튼 연결하기
- [x] 읽은 책으로 추가하기 버튼 토글로 변경하기
