### ISSUE TITLE
[feat] 마이페이지 책 셀 UI 구현

### ISSUE THREAD

**Issue by rafa-e1** [BOOK-TALK/Readables-iOS#99]
## 📚  이슈

마이페이지 책 셀 UI 구현

## 📝  To-do

- [x] 읽은 책 및 찜한 도서 셀 구현하기
- [x] 데이터 전달해 보기
- [x] 레이아웃 깨짐 현상 해결하기
